"""Figure provenance and protected experiment execution; paper snapshot stays untouched."""
import datetime as dt
import json
from pathlib import Path
import subprocess
import sys
import streamlit as st

ROOT = Path(__file__).resolve().parents[2]
st.set_page_config(page_title="IT2: reproduce the study", page_icon="🔬", layout="wide")
st.title("How the study results were obtained")
st.info("The Study results tab displays the saved paper snapshot. This page explains its sources and can rerun selected stages in a separate folder.")
st.subheader("Problem, method and evidence")
st.markdown("""A digital twin can lose its links when a revised IFC model changes element identifiers.
Separately, equipment may belong to a named system without having modelled port connections.
IT2 checks these two assumptions explicitly: reconcile element identity, then audit the port network.
The experiments use real IFC geometry with controlled simulated revisions, so the correct element pairs are known.
The binding-validity experiment uses simulated equipment bindings; it is not a measurement from a live BMS.""")
st.markdown("**Topology:** nodes are distribution elements; edges come from IFC port-connection relations.")
st.latex(r"PC=\frac{\#\text{elements with ports}}{\#\text{distribution elements}},\quad LC=\frac{\#\text{elements in largest component}}{\#\text{distribution elements}},\quad SM=\frac{\#\text{elements in an IFC system}}{\#\text{distribution elements}}")
st.markdown("**Identity:** the experimental hybrid first matches class and Tag, then uses Hungarian assignment within class/container partitions. Remaining candidates are scored by bounding-box centre distance, dimension differences and a type-name penalty; assignments above the rejection gate are discarded. The real-use app also tries unchanged GlobalIds first.")
st.latex(r"C_{ij}=\|c_i-c_j\|_2+\|d_i-d_j\|_1+\lambda\,\mathbf{1}[t_i\ne t_j],\qquad C_{ij}\le\tau")
st.caption("The simulator preserves each surviving element's dimensions and type name, adds small position noise, moves selected elements, changes selected Tags, deletes elements and adds decoys. These assumptions limit what the results establish.")

# Keep evidence type beside each figure: diagrams, experiments and proposed work differ.
FIGURES = [
    ("f1_loops.png", "Conceptual", "Problem feedback loops", "Authored diagram; not calculated from experimental measurements", ["scripts/07_figures.py"]),
    ("f2_design.png", "Conceptual", "Research design", "Authored design diagram describing the study", ["scripts/07_figures.py"]),
    ("f3_protocol.png", "Proposed protocol", "IT2 acceptance protocol", "IDS, BOT/Brick and BCF stages are a proposed workflow; this repository does not implement those integrations", ["scripts/07_figures.py"]),
    ("f4_quadrant.png", "Empirical", "System membership versus port coverage", "Seven IFC models → topology.json → figure", ["data/download.py", "it2/topology.py", "scripts/01_topology.py", "scripts/07_figures.py"]),
    ("f5_recall.png", "Controlled experiment", "Recall versus recreated share", "Three model fingerprints; 20 seeds per share (0, .1, .2, .3, .5); 95% bootstrap intervals", ["it2/features.py", "scripts/02_extract_features.py", "it2/matching.py", "scripts/03_identity.py", "scripts/07_figures.py"]),
    ("f6_sensitivity.png", "Controlled experiment", "Sensitivity to lambda and tau", "Two models; 5 seeds per grid cell; all Tags recreated, 30% moved with sigma=.3 m; displays mean F1", ["it2/matching.py", "scripts/04_sensitivity_bv.py", "scripts/07_figures.py"]),
    ("f7_roadmap.png", "Proposed future work", "Research roadmap", "Authored work plan; future stages are not completed experiments", ["scripts/07_figures.py"]),
]
st.subheader("Every figure and its generating code")
st.dataframe([{"Figure": f, "Evidence type": kind, "Meaning": title, "Source": source}
              for f, kind, title, source, _ in FIGURES], hide_index=True, width="stretch")
for name, kind, title, explanation, scripts in FIGURES:
    with st.expander(f"{name}: {title} ({kind})"):
        st.write(explanation)
        st.image(str(ROOT / "figures" / name), width="stretch")
        for source in scripts:
            with st.expander(f"View source: {source}"):
                st.code((ROOT / source).read_text(encoding="utf-8"), language="python")
st.subheader("Other result files")
st.markdown("""- `extra_*.json`: sensitivity and simulated binding validity, generated by `04_sensitivity_bv.py`.
- `roundtrip_*.json`: revised IFC geometry and truth mappings, generated by `05_roundtrip.py`.
- `roundtrip_eval.json`: file-level versus feature-level comparison, generated by `06_eval_roundtrip.py`.

The file-level experiment uses three seeds for each of two configurations; its feature-level comparison uses 20 seeds.
The seven downloaded models are not seven independent buildings. Results describe these models and controlled conditions, not universal exporter performance.""")

st.subheader("Reproduce without changing paper results")
choices = {
    "Render figures from saved results": "figures",
    "Rerun experiments from supplied fingerprints": "saved-features",
    "Full reproduction from raw IFC models": "raw-ifc",
}
label = st.selectbox("Reproduction scope", list(choices))
st.caption("Rendering does not validate experiments. Fingerprint mode recalculates identity, sensitivity, binding validity and round-trip evaluation, but reuses saved fingerprints and file-level round-trip records. Raw mode includes downloads, geometry extraction and new file-level revisions, and can take substantially longer.")
active = st.session_state.get("it2_reproduction")
running = active is not None and active["process"].poll() is None
# The experiment runs in a child process so the app stays responsive.
if st.button("Run selected stages in a separate folder", type="primary", disabled=running):
    output = ROOT.parent / "it2-reproduction" / dt.datetime.now().strftime("%Y%m%d-%H%M%S-%f")
    output.parent.mkdir(parents=True, exist_ok=True)
    log_path = output.parent / (output.name + ".log")
    with log_path.open("w", encoding="utf-8") as log:
        process = subprocess.Popen([sys.executable, str(ROOT / "scripts/reproduce_study.py"),
                                    "--mode", choices[label], "--output", str(output)],
                                   cwd=ROOT, stdout=log, stderr=subprocess.STDOUT)
    st.session_state["it2_reproduction"] = {"process": process, "output": output, "log": log_path}
    st.rerun()
active = st.session_state.get("it2_reproduction")
if active:
    code = active["process"].poll()
    st.write(f"Output folder: {active['output']}")
    if code is None:
        st.info("Reproduction is running. Refresh the status to see progress.")
    elif code == 0:
        st.success("Selected stages completed. Inspect the report for the validated scope and comparisons.")
    else:
        st.error(f"Run exited with code {code}; inspect the log and report. Original paper files are preserved.")
    st.button("Refresh run status")
    log = active["log"].read_text(encoding="utf-8", errors="replace")
    st.code(log[-15000:], language="text")
    # Show the machine-readable audit alongside the log; do not silently replace paper outputs.
    report = active["output"] / "reproduction_report.json"
    if report.exists():
        raw = report.read_bytes()
        st.json(json.loads(raw))
        st.download_button("Download reproduction report", raw, "reproduction_report.json", "application/json")
    produced = active["output"] / "workspace/figures"
    if code == 0 and produced.exists():
        with st.expander("View figures from this reproduction run"):
            for figure in sorted(produced.glob("*.png")):
                st.image(str(figure), caption=figure.name, width="stretch")
st.caption("Known Windows path issues are adapted only in the reproduction copy: IFC basenames and the round-trip temporary directory. No matching equations, thresholds or paper data are changed.")
